version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: gunicorn comment.wsgi:application --bind 0.0.0.0:8000

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: commentdb
      POSTGRES_USER: commentuser
      POSTGRES_PASSWORD: *
